### ISSUE TITLE
Crate versioning

### ISSUE THREAD

**Issue by clux** [kube-rs/k8s-pb#10]
We **should not** export version features in this crate ala `k8s-openapi`:

- They really annoying to use with resolver2 workspaces -> people have to select a version, even though they are not using anything other than metadata for some `kube_core` structs.

- They send a **false** message that hardcoding the kubernetes version in your toml is necessary, when in reality, kubernetes is not breaking any apis (they release new versions of them and remove deprecated ones).

- It also ends up being [impossible to run workspace tests on a matrix of kubernetes version](https://github.com/kube-rs/kube-rs/issues/684#issuecomment-953572644) in `kube-rs` when the versions are features because dev-deps need to select one version, and then we can't unselect the dev-dep version for tests.

We COULD re-export the features ourselves (and re-export the structs), but they end up everywhere in the tomls:
<details><summary>kube cargo.toml</summary>
<p>

```toml
# Supported kubernetes versions
v1_17 = ["k8s-openapi/v1_17", "kube-core/v1_17", "kube-client/v1_17", "kube-runtime/v1_17"]
v1_18 = ["k8s-openapi/v1_18", "kube-core/v1_18", "kube-client/v1_18", "kube-runtime/v1_18"]
v1_19 = ["k8s-openapi/v1_19", "kube-core/v1_19", "kube-client/v1_19", "kube-runtime/v1_19"]
v1_20 = ["k8s-openapi/v1_20", "kube-core/v1_20", "kube-client/v1_20", "kube-runtime/v1_20"]
v1_21 = ["k8s-openapi/v1_21", "kube-core/v1_21", "kube-client/v1_21", "kube-runtime/v1_21"]
v1_22 = ["k8s-openapi/v1_22", "kube-core/v1_22", "kube-client/v1_22", "kube-runtime/v1_22"]
```
</p>
</details>

and we still have to set a default version for us to run `cargo build` with this way (otherwise it would be super impractical for us). If we set a default version feature, then we need to unselect them for matrix CI, and cascade non-defaults everywhere, leading to a nightmare of features and dev-deps again.

### Proposal
We should define our own `client-go` like [compatibility matrix](https://github.com/kubernetes/client-go#compatibility-matrix).
This heavily matches what we want. It reflects the guarantees we really have (apis either disappear because they are deprecated+removed, or are not in that version of kube because we didn't use a new enough codegen).

That way we simply announce that kube has at least these api features available, and newer versions of kube might lack some deprecated apis that were removed by kubernetes in this version.
